server {
    listen 80;
    
    server_name localhost;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        # Fallback to index.html for React Router
        try_files $uri $uri/ /index.html;
    }

    # Optional: Proxy API requests to backend if needed (though typically handled by absolute URL or Env Var in production pointing to full backend URL)
    # location /api {
    #     proxy_pass http://backend:5000;
    # }
}
