"""Init

Revision ID: 509520dfa814
Revises: 
Create Date: 2025-12-25 17:53:34.450160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '509520dfa814'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faculty',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('institution', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('research_interests', sa.JSON(), nullable=True),
    sa.Column('profile_image', sa.Text(), nullable=True),
    sa.Column('citations', sa.Integer(), nullable=True),
    sa.Column('h_index', sa.Integer(), nullable=True),
    sa.Column('google_scholar_url', sa.String(length=255), nullable=True),
    sa.Column('orcid_id', sa.String(length=255), nullable=True),
    sa.Column('irins_profile_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('faculty', schema=None) as batch_op:
        batch_op.create_index('idx_faculty_fulltext', ['name', 'department', 'institution'], unique=False, mysql_prefix='FULLTEXT')

    op.create_table('publications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('authors', sa.JSON(), nullable=True),
    sa.Column('journal', sa.String(length=255), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('doi', sa.String(length=255), nullable=True),
    sa.Column('citations', sa.Integer(), nullable=True),
    sa.Column('venue', sa.String(length=255), nullable=True),
    sa.Column('publisher', sa.String(length=255), nullable=True),
    sa.Column('research_domains', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('publications', schema=None) as batch_op:
        batch_op.create_index('idx_publication_fulltext', ['title', 'abstract'], unique=False, mysql_prefix='FULLTEXT')

    op.create_table('research_trends',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('topic', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('growth_rate', sa.Float(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('quarter', sa.Integer(), nullable=True),
    sa.Column('publication_count', sa.Integer(), nullable=True),
    sa.Column('citation_count', sa.Integer(), nullable=True),
    sa.Column('faculty_count', sa.Integer(), nullable=True),
    sa.Column('trending_score', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('research_works',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('researcher', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.Column('funding', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('research_works', schema=None) as batch_op:
        batch_op.create_index('idx_research_work_fulltext', ['title', 'description', 'domain'], unique=False, mysql_prefix='FULLTEXT')

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('faculty_publications',
    sa.Column('faculty_id', sa.String(length=36), nullable=False),
    sa.Column('publication_id', sa.String(length=36), nullable=False),
    sa.Column('author_position', sa.Integer(), nullable=True),
    sa.Column('is_corresponding', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculty.id'], ),
    sa.ForeignKeyConstraint(['publication_id'], ['publications.id'], ),
    sa.PrimaryKeyConstraint('faculty_id', 'publication_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('faculty_publications')
    op.drop_table('users')
    with op.batch_alter_table('research_works', schema=None) as batch_op:
        batch_op.drop_index('idx_research_work_fulltext', mysql_prefix='FULLTEXT')

    op.drop_table('research_works')
    op.drop_table('research_trends')
    with op.batch_alter_table('publications', schema=None) as batch_op:
        batch_op.drop_index('idx_publication_fulltext', mysql_prefix='FULLTEXT')

    op.drop_table('publications')
    with op.batch_alter_table('faculty', schema=None) as batch_op:
        batch_op.drop_index('idx_faculty_fulltext', mysql_prefix='FULLTEXT')

    op.drop_table('faculty')
    # ### end Alembic commands ###
